version: '3'

services:
  minecraft-server:
    image: itzg/minecraft-bedrock-server:latest
    container_name: minecraft-bedrock
    # サーバー、Dockerデーモンの再起動でマイクラサーバーも起動します。
    restart: always
    env_file:
      - ./mc.env
    environment:
      # eula(ソフトウェア使用許諾契約)に同意します。
      EULA: "TRUE"
      VERSION: "LATEST"
    volumes:
      - /var/mc_bedrock_data:/data
    ports:
      - 80:25565

